In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('50_Startups.csv')

In [ ]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
data2 = pd.get_dummies(data, columns = ['State'])
data2.head()

R&D Spend  Administration  Marketing Spend     Profit  State_California  \
0  165349.20       136897.80        471784.10  192261.83                 0   
1  162597.70       151377.59        443898.53  191792.06                 1   
2  153441.51       101145.55        407934.54  191050.39                 0   
3  144372.41       118671.85        383199.62  182901.99                 0   
4  142107.34        91391.77        366168.42  166187.94                 0   

   State_Florida  State_New York  
0              0               1  
1              0               0  
2              1               0  
3              0               1  
4              1               0

In [ ]:
data2.isna().any()

R&D Spend           False
Administration      False
Marketing Spend     False
Profit              False
State_California    False
State_Florida       False
State_New York      False
dtype: bool

In [ ]:
data2.isnull().any()

R&D Spend           False
Administration      False
Marketing Spend     False
Profit              False
State_California    False
State_Florida       False
State_New York      False
dtype: bool

In [ ]:
features = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
fState=ohe.fit_transform(features[:,3].reshape(-1,1))
fState

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [ ]:
x = np.concatenate((fState,features[:,[0,1,2]]) , axis = 1)

In [ ]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [ ]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
trainx, testx, trainy, testy = train_test_split(x,y, test_size=.25)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(trainx, trainy)

LinearRegression()

In [ ]:
model.score(testx,testy)

0.9760762611076489

In [ ]:
model.score(trainx,trainy)

0.9359879268816107

In [ ]:
model.predict([[1,0,0,165893,136985,471562]])

array([190521.5795045])

In [ ]:
ohe.transform(np.array([['California']]))

array([[1., 0., 0.]])

In [ ]:
ohe.transform(np.array([['Florida']]))

array([[0., 1., 0.]])

In [ ]:
list(ohe.categories_)[0]

array(['California', 'Florida', 'New York'], dtype=object)

In [ ]:
#Deploy Test

rdSpend = float(input("Enter R&D cost: "))
admSpend = float(input("Enter Admin cost: "))
markSpend = float(input("Enter Marketing cost: "))
state = input("Enter State: ")

if state not in list(ohe.categories_)[0]:
    print("State not identified by the AI model !")
else:
    stateDummyVariable = ohe.transform(np.array([[state]]))
    compatibleFeatureSet = np.concatenate((stateDummyVariable, np.array([[rdSpend,admSpend,markSpend]])) , axis=1 )
    #scaledFeatureSet = objStandardScaler.transform(compatibleFeatureSet)
    profit = model.predict(compatibleFeatureSet)
    print("As per model's knowledge, the company may earn a profit of $ {} based on current spending pattern and location ".format(round(profit[0])))
    
#Datatype: numpy array Dim: 2

Enter R&D cost: 123456
Enter Admin cost: 321654
Enter Marketing cost: 876541
Enter State: New York
As per model's knowledge, the company may earn a profit of $ 169984 based on current spending pattern and location 


In [ ]:
salary = pd.read_csv('Salary_Data.csv')

In [ ]:
salary.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
exp = salary.iloc[:,:-1].values
sal = salary.iloc[:,-1].values
exp

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
sal

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [ ]:
train_x,test_x,train_y,test_y = train_test_split(exp,sal, test_size=0.25,random_state=1)

In [ ]:
model2 = LinearRegression()
model2.fit(train_x,train_y)

LinearRegression()

In [ ]:
model2.predict([[1.4]])

array([38858.5015533])

In [ ]:
model2.score(train_x,train_y)

0.9631627885810901

In [ ]:
model2.score(test_x,test_y)

0.9180980074804029

In [ ]:
#deployment

years = float(input("Enter Years of experience: "))

pred_salary = model2.predict([[years]])

print('The salary is: $ {}'.format(round(pred_salary[0])))

Enter Years of experience: 1.4
The salary is: $ 38859


In [ ]:
import pickle

In [ ]:
pickle.dump(model2,open('YearsOfExp.mdl','wb'))

In [ ]:
pickle.dump(model,open('StateEncoder.obj','wb'))